# Generated by Django 3.0.6 on 2020-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_formulario', '0002_usuario_publicidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='publicidad',
            field=models.BooleanField(default=False),
        ),
    ]
