# Generated by Django 3.0.6 on 2020-05-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_anuncio_usuario'),
        ('anuncios', '0002_auto_20200507_0952'),
        ('anuncios', '0004_auto_20200507_1056'),
    ]

    operations = [
    ]
