# Generated by Django 3.0.6 on 2020-05-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0007_auto_20200514_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='ultima_modificacion',
        ),
    ]
