# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_registro.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 581, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_marca = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_marca.setGeometry(QtCore.QRect(140, 110, 311, 20))
        self.txt_marca.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_marca.setObjectName("txt_marca")
        self.txt_modelo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_modelo.setGeometry(QtCore.QRect(140, 180, 311, 20))
        self.txt_modelo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_modelo.setObjectName("txt_modelo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_color = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_color.setGeometry(QtCore.QRect(140, 250, 311, 20))
        self.txt_color.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_color.setObjectName("txt_color")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 250, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_motor = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_motor.setGeometry(QtCore.QRect(140, 320, 311, 20))
        self.txt_motor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_motor.setObjectName("txt_motor")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 320, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txt_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_precio.setGeometry(QtCore.QRect(140, 390, 311, 20))
        self.txt_precio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_precio.setObjectName("txt_precio")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 390, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_registrar.setGeometry(QtCore.QRect(220, 520, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_registrar.setFont(font)
        self.btn_registrar.setObjectName("btn_registrar")
        self.lbl_marca_ko = QtWidgets.QLabel(self.centralwidget)
        self.lbl_marca_ko.setGeometry(QtCore.QRect(480, 110, 281, 20))
        self.lbl_marca_ko.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_marca_ko.setText("")
        self.lbl_marca_ko.setObjectName("lbl_marca_ko")
        self.lbl_modelo_ko = QtWidgets.QLabel(self.centralwidget)
        self.lbl_modelo_ko.setGeometry(QtCore.QRect(480, 180, 281, 20))
        self.lbl_modelo_ko.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_modelo_ko.setText("")
        self.lbl_modelo_ko.setObjectName("lbl_modelo_ko")
        self.lbl_color_ko = QtWidgets.QLabel(self.centralwidget)
        self.lbl_color_ko.setGeometry(QtCore.QRect(480, 250, 281, 20))
        self.lbl_color_ko.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_color_ko.setText("")
        self.lbl_color_ko.setObjectName("lbl_color_ko")
        self.lbl_motor_ko = QtWidgets.QLabel(self.centralwidget)
        self.lbl_motor_ko.setGeometry(QtCore.QRect(480, 320, 281, 20))
        self.lbl_motor_ko.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_motor_ko.setText("")
        self.lbl_motor_ko.setObjectName("lbl_motor_ko")
        self.lbl_precio_ko = QtWidgets.QLabel(self.centralwidget)
        self.lbl_precio_ko.setGeometry(QtCore.QRect(480, 390, 281, 20))
        self.lbl_precio_ko.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_precio_ko.setText("")
        self.lbl_precio_ko.setObjectName("lbl_precio_ko")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 460, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txt_forma_pago = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_forma_pago.setGeometry(QtCore.QRect(140, 460, 311, 20))
        self.txt_forma_pago.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_forma_pago.setObjectName("txt_forma_pago")
        self.lbl_forma_pago_ko = QtWidgets.QLabel(self.centralwidget)
        self.lbl_forma_pago_ko.setGeometry(QtCore.QRect(480, 460, 281, 20))
        self.lbl_forma_pago_ko.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_forma_pago_ko.setText("")
        self.lbl_forma_pago_ko.setObjectName("lbl_forma_pago_ko")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">REGISTRO DE COCHES :</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "MARCA"))
        self.label_3.setText(_translate("MainWindow", "MODELO"))
        self.label_4.setText(_translate("MainWindow", "COLOR"))
        self.label_5.setText(_translate("MainWindow", "MOTOR"))
        self.label_6.setText(_translate("MainWindow", "PRECIO"))
        self.btn_registrar.setText(_translate("MainWindow", "REGISTRAR"))
        self.label_7.setText(_translate("MainWindow", "FORMA PAGO"))
