# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_edicion.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 581, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_marca = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_marca.setGeometry(QtCore.QRect(140, 110, 401, 20))
        self.txt_marca.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_marca.setObjectName("txt_marca")
        self.txt_modelo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_modelo.setGeometry(QtCore.QRect(140, 180, 401, 20))
        self.txt_modelo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_modelo.setObjectName("txt_modelo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_color = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_color.setGeometry(QtCore.QRect(140, 250, 401, 20))
        self.txt_color.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_color.setObjectName("txt_color")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 250, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_motor = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_motor.setGeometry(QtCore.QRect(140, 320, 401, 20))
        self.txt_motor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_motor.setObjectName("txt_motor")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 320, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txt_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_precio.setGeometry(QtCore.QRect(140, 400, 401, 20))
        self.txt_precio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_precio.setObjectName("txt_precio")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 400, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_modificar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_modificar.setGeometry(QtCore.QRect(240, 510, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_modificar.setFont(font)
        self.btn_modificar.setObjectName("btn_modificar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 470, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txt_forma_pago = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_forma_pago.setGeometry(QtCore.QRect(140, 470, 401, 20))
        self.txt_forma_pago.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txt_forma_pago.setObjectName("txt_forma_pago")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Modificar registro"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">MODIFICAR COCHE</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "MARCA"))
        self.label_3.setText(_translate("MainWindow", "MODELO"))
        self.label_4.setText(_translate("MainWindow", "COLOR"))
        self.label_5.setText(_translate("MainWindow", "MOTOR"))
        self.label_6.setText(_translate("MainWindow", "PRECIO"))
        self.btn_modificar.setText(_translate("MainWindow", "MODIFICAR"))
        self.label_7.setText(_translate("MainWindow", "FORMA PAGO"))
