SELECT DEPT.DEPTNO, 
	   DEPT.DEPTNAME, 
	   COALESCE(SUM(EMPL.SALARY), 0) AS MASA_SALARIAL

FROM DEPARTMENT AS DEPT LEFT JOIN EMPLOYEE AS EMPL

ON DEPT.DEPTNO = EMPL.WORKDEPT

GROUP BY DEPT.DEPTNO, DEPT.DEPTNAME

ORDER BY MASA_SALARIAL DESC