
SELECT V1.RESPONSABLE, V1.MEDIA, V2.NOMBRE, V2.APELLIDO
	FROM
		(SELECT RESPONSABLE, 
		 		ROUND(AVG(SALARIO), 2) AS MEDIA		 		
				FROM VENDEDOR
				GROUP BY RESPONSABLE
				HAVING AVG(SALARIO ) > '22000') AS V1 
			
			JOIN VENDEDOR V2
			
			ON V1.RESPONSABLE = V2.VENDEDOR
