/*1.- MOSTRAR EL NOMBRE DEL EMPLEADO JUNTO AL NOMBRE DEL HIJO.*/

--SELECT TEMPLA.NOMBRE, TEMPLA.APELLIDO, HIJOS.NOMBRE, HIJOS.APELLIDO

--FROM TEMPLA INNER JOIN HIJOS
--ON TEMPLA.NUEMPL = HIJOS.NUEMPL;

/* 2.- LO MISMO QUE ANTES, PERO TAMBIEN MOSTRAMOS LOS NOMBRES DE LOS 
    EMPLEADOS SIN HIJOS, INDICANDO " SIN HIJOS " EN EL NOMBRE DEL HIJO. */
    
SELECT  TEMPLA.NUEMPL, TEMPLA.NOMBRE, TEMPLA.APELLIDO, 
        CONCAT(HIJOS.NOMBRE, " ", HIJOS.APELLIDO) AS HIJOS

FROM TEMPLA LEFT JOIN HIJOS

ON TEMPLA.NUEMPL = HIJOS.NUEMPL;

