SELECT  C.CLIENTE,
		C.TIPO,
	    C.NOMBRE,
	    C.APELLIDO1,
	    C.APELLIDO2,
	    C.VENDEDOR,
	    (X.ANYO_ACTUAL + X.ANYO_ANT + X.ANYO_DOS_ANT + X.ANYO_TRE_ANT + X.ANYO_CUA_ANT) AS TOTAL_COMPRAS

FROM CLIENTES C JOIN COMPCLIE X ON C.CLIENTE = X.CLIENTE

ORDER BY TOTAL_COMPRAS DESC;

