# Generated by Django 3.0.6 on 2020-05-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_usuarios_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellido2',
            new_name='apellido_2',
        ),
    ]
