# Generated by Django 3.0.6 on 2020-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_auto_20200508_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
