# Generated by Django 3.0.6 on 2020-05-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_auto_20200507_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anuncios.Usuario'),
            preserve_default=False,
        ),
    ]
