# Generated by Django 3.0.6 on 2020-05-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_merge_20200514_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='ip',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='ultima_modificacion',
            field=models.DateTimeField(default=1, verbose_name='fecha ultima modificacion'),
            preserve_default=False,
        ),
    ]
