# Generated by Django 3.0.6 on 2020-05-14 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_remove_anuncio_ultima_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='ultima_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha ultima modificacion'),
            preserve_default=False,
        ),
    ]
