# Generated by Django 3.0.6 on 2020-05-15 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_auto_20200508_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='perros',
            name='ultima_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha ultima modificacion'),
            preserve_default=False,
        ),
    ]
