# Generated by Django 3.0.6 on 2020-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_perros_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email_validado',
            field=models.BooleanField(default=False),
        ),
    ]
