# Generated by Django 3.0.6 on 2020-05-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_perros_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='perros',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Categorias'),
        ),
        migrations.AddField(
            model_name='perros',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anuncios.Usuarios'),
            preserve_default=False,
        ),
    ]
