# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_asistente.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 50, 481, 51))
        self.label.setObjectName("label")
        self.cbx_marca = QtWidgets.QComboBox(self.centralwidget)
        self.cbx_marca.setGeometry(QtCore.QRect(150, 130, 350, 22))
        self.cbx_marca.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_marca.setObjectName("cbx_marca")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.txt_modelo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_modelo.setGeometry(QtCore.QRect(150, 180, 350, 20))
        self.txt_modelo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_modelo.setObjectName("txt_modelo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 230, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.cbx_color = QtWidgets.QComboBox(self.centralwidget)
        self.cbx_color.setGeometry(QtCore.QRect(150, 230, 350, 22))
        self.cbx_color.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_color.setObjectName("cbx_color")
        self.cbx_color.addItem("")
        self.cbx_color.addItem("")
        self.cbx_color.addItem("")
        self.cbx_color.addItem("")
        self.cbx_color.addItem("")
        self.cbx_color.addItem("")
        self.cbx_color.addItem("")
        self.radio_diesel = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_diesel.setGeometry(QtCore.QRect(150, 290, 82, 17))
        self.radio_diesel.setObjectName("radio_diesel")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 310, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.radio_gasolina = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_gasolina.setGeometry(QtCore.QRect(150, 330, 82, 17))
        self.radio_gasolina.setChecked(True)
        self.radio_gasolina.setObjectName("radio_gasolina")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 410, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.spx_precio = QtWidgets.QSpinBox(self.centralwidget)
        self.spx_precio.setGeometry(QtCore.QRect(150, 410, 350, 22))
        self.spx_precio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spx_precio.setMinimum(90000)
        self.spx_precio.setMaximum(999999)
        self.spx_precio.setSingleStep(10000)
        self.spx_precio.setObjectName("spx_precio")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 510, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.chx_cheque = QtWidgets.QCheckBox(self.centralwidget)
        self.chx_cheque.setGeometry(QtCore.QRect(150, 510, 101, 17))
        self.chx_cheque.setObjectName("chx_cheque")
        self.chx_tarjeta = QtWidgets.QCheckBox(self.centralwidget)
        self.chx_tarjeta.setGeometry(QtCore.QRect(250, 510, 101, 17))
        self.chx_tarjeta.setObjectName("chx_tarjeta")
        self.chx_contado = QtWidgets.QCheckBox(self.centralwidget)
        self.chx_contado.setGeometry(QtCore.QRect(350, 510, 101, 17))
        self.chx_contado.setObjectName("chx_contado")
        self.btn_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_registrar.setGeometry(QtCore.QRect(250, 550, 151, 31))
        self.btn_registrar.setStyleSheet("background-color: rgb(157, 148, 255);")
        self.btn_registrar.setObjectName("btn_registrar")
        self.chx_financiado = QtWidgets.QCheckBox(self.centralwidget)
        self.chx_financiado.setGeometry(QtCore.QRect(450, 510, 101, 17))
        self.chx_financiado.setObjectName("chx_financiado")
        self.lbl_marca_ko = QtWidgets.QLabel(self.centralwidget)
        self.lbl_marca_ko.setGeometry(QtCore.QRect(530, 130, 221, 20))
        self.lbl_marca_ko.setText("")
        self.lbl_marca_ko.setObjectName("lbl_marca_ko")
        self.lbl_modelo_ko = QtWidgets.QLabel(self.centralwidget)
        self.lbl_modelo_ko.setGeometry(QtCore.QRect(530, 180, 221, 20))
        self.lbl_modelo_ko.setText("")
        self.lbl_modelo_ko.setObjectName("lbl_modelo_ko")
        self.lbl_color_ko = QtWidgets.QLabel(self.centralwidget)
        self.lbl_color_ko.setGeometry(QtCore.QRect(530, 230, 221, 20))
        self.lbl_color_ko.setText("")
        self.lbl_color_ko.setObjectName("lbl_color_ko")
        self.lbl_modo_pago_ko = QtWidgets.QLabel(self.centralwidget)
        self.lbl_modo_pago_ko.setGeometry(QtCore.QRect(550, 510, 231, 20))
        self.lbl_modo_pago_ko.setText("")
        self.lbl_modo_pago_ko.setObjectName("lbl_modo_pago_ko")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">ASISTENTE PARA REGISTRO DE COCHES</span></p></body></html>"))
        self.cbx_marca.setItemText(0, _translate("MainWindow", "--------- elegir ---------"))
        self.cbx_marca.setItemText(1, _translate("MainWindow", "Ferrari"))
        self.cbx_marca.setItemText(2, _translate("MainWindow", "Lamborghini"))
        self.cbx_marca.setItemText(3, _translate("MainWindow", "Lotus"))
        self.cbx_marca.setItemText(4, _translate("MainWindow", "McLaren"))
        self.cbx_marca.setItemText(5, _translate("MainWindow", "Porsche"))
        self.cbx_marca.setItemText(6, _translate("MainWindow", "Mazda"))
        self.cbx_marca.setItemText(7, _translate("MainWindow", "Ford"))
        self.cbx_marca.setItemText(8, _translate("MainWindow", "BMW"))
        self.cbx_marca.setItemText(9, _translate("MainWindow", "Mercedes"))
        self.label_2.setText(_translate("MainWindow", "MARCA"))
        self.label_3.setText(_translate("MainWindow", "MODELO"))
        self.label_4.setText(_translate("MainWindow", "COLOR"))
        self.cbx_color.setItemText(0, _translate("MainWindow", "--------- elegir ---------"))
        self.cbx_color.setItemText(1, _translate("MainWindow", "amarillo"))
        self.cbx_color.setItemText(2, _translate("MainWindow", "rojo"))
        self.cbx_color.setItemText(3, _translate("MainWindow", "azul"))
        self.cbx_color.setItemText(4, _translate("MainWindow", "gris"))
        self.cbx_color.setItemText(5, _translate("MainWindow", "naranja"))
        self.cbx_color.setItemText(6, _translate("MainWindow", "negro"))
        self.radio_diesel.setText(_translate("MainWindow", "  Diesel"))
        self.label_5.setText(_translate("MainWindow", "MOTOR"))
        self.radio_gasolina.setText(_translate("MainWindow", "  Gasolina"))
        self.label_6.setText(_translate("MainWindow", "PRECIO"))
        self.label_7.setText(_translate("MainWindow", "MEDIO DE PAGO"))
        self.chx_cheque.setText(_translate("MainWindow", " Cheque"))
        self.chx_tarjeta.setText(_translate("MainWindow", " Tarjeta"))
        self.chx_contado.setText(_translate("MainWindow", " Contado"))
        self.btn_registrar.setText(_translate("MainWindow", "REGISTRAR"))
        self.chx_financiado.setText(_translate("MainWindow", " Financiado"))
