CREATE TABLE PEDROC.VENDEDOR LIKE FORMA2.VENDEDOR;

INSERT INTO PEDROC.VENDEDOR
SELECT * FROM FORMA2.VENDEDOR;

CREATE TABLE PEDROC.CLIENTE_CORTO LIKE FORMA2.CLIENTE_CORTO;

INSERT INTO PEDROC.CLIENTE_CORTO
SELECT CLIENTE, NOMBRE, APELLIDO1, TELEFONO, CODPOSTAL, COMPRAS_ANUAL
FROM FORMA2.CLIENTES;