/*2.1- MOSTRAR EL NOMBRE DEL EMPLEADO, EL NOMBRE DEL CONYUGE Y EL NOMBRE 
     DEL HIJO.*/
   
SELECT 	TEMPLA.NUEMPL, CONCAT(TEMPLA.NOMBRE, " ", TEMPLA.APELLIDO) NOM_EMPL, 
		CONCAT(CONYUGES.NOMBRE, " ", CONYUGES.APELLIDO) NOM_CONYUG, 
		CONCAT(HIJOS.NOMBRE, " ", HIJOS.APELLIDO) AS NOM_HIJOS

FROM TEMPLA INNER JOIN CONYUGES

ON TEMPLA.NUEMPL = CONYUGES.NUEMPL
	INNER JOIN HIJOS
		ON TEMPLA.NUEMPL = HIJOS.NUEMPL