/*2.1- MOSTRAR EL NOMBRE DEL EMPLEADO, EL NOMBRE DEL CONYUGE Y EL NOMBRE 
     DEL HIJO.*/

SELECT TEMPLA.NUEMPL, 
		 COALESCE(CONCAT(TEMPLA.NOMBRE, " ", TEMPLA.APELLIDO), "NO TIENE") AS NOM_EMPL, 
		 COALESCE(CONCAT(CONYUGES.NOMBRE, " ", CONYUGES.APELLIDO), "NO TIENE") AS NOM_CONYUG, 
		 COALESCE(CONCAT(HIJOS.NOMBRE, " ", HIJOS.APELLIDO), "NO TIENE") AS NOM_HIJOS

FROM TEMPLA LEFT JOIN CONYUGES
ON TEMPLA.NUEMPL = CONYUGES.NUEMPL

	LEFT JOIN HIJOS
	ON TEMPLA.NUEMPL = HIJOS.NUEMPL
	
ORDER BY TEMPLA.NUEMPL;