/* 15.-   CREAR UNA VISTA PARA MOSTRAR DE FORMA FACIL EL N�MERO DE CLIENTE, EL NOMBRE Y APELLIDOS
       DEL CLIENTE, FECHA DE NACIMIENTO, COMPRAS ANUALES, JUNTO CON EL CODIGO, NOMBRE Y APELLIDO
       DEL VENDEDOR.	 */

CREATE VIEW PEDROC.V_CLIENTES 
       (COD_CLIENTE, NOMBRE_CLIENTE , APELLIDO1, APELLIDO2, FECHA_NAC, COMPRAS_ANUAL, 
	COD_VENDEDOR, NOMBRE_VENDEDOR, APELLIDO_VENDEDOR)
AS 
SELECT CLIENTE, C.NOMBRE, APELLIDO1, APELLIDO2, FX_NACIMIENTO, COMPRAS_ANUAL, C.VENDEDOR, V.NOMBRE, V.APELLIDO
FROM PEDROC.CLIENTES C
LEFT JOIN PEDROC.VENDEDOR V
ON C.VENDEDOR = V.VENDEDOR;

SELECT *
FROM PEDROC.V_CLIENTES;

CREATE TABLE PEDROC.CLIEPRU LIKE FORMA2.CLIENTES;

SELECT *
FROM PEDROC.CLIEPRU

CREATE UNIQUE INDEX PEDROC.IX_CLIENTE_1
ON PEDROC.CLIEPRU (CLIENTE);

CREATE INDEX PEDROC.IX_CLIENTE_2
ON PEDROC.CLIEPRU (APELLIDO1, APELLIDO2, NOMBRE);

SELECT *
FROM PEDROC.CLIEPRU;

DROP INDEX PEDROC.IX_CLIENTE2;

INSERT INTO PEDROC.CLIEPRU
SELECT *
FROM FORMA2.CLIENTES;

SELECT *
FROM PEDROC.CLIEPRU c;

ALTER TABLE PEDROC.CLIEPRU
ADD CYBERCLIENTE CHAR(1);

CREATE VIEW PEDROC.V_CLI_PART
AS
SELECT *
FROM PEDROC.CLIEPRU
WHERE EMPRESA IS NOT NULL;

SELECT *
FROM PEDROC.V_CLI_PART;

/* ahora una vista para listar los clientes que son de empresa, mostrando el
c�digo, nombre, apellidos y tel�fono del cliente, junto con el nombre, direcci�n
y provincia de la empresa. La vista se debe llamar V_CLI_EMP */

CREATE VIEW PEDROC.VI_CLI_EMP
AS
SELECT CLIENTE, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, EMPRESA, DS_EMPRESA, DIRECCION, PROVINCIA
FROM PEDROC.CLIEPRU PC
JOIN FORMA2.EMPRESAS FE
ON PC.EMPRESA = FE.CO_EMPRESA;

SELECT *
FROM PEDROC.VI_CLI_EMP;

