# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registro_revista.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 30, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.entrada_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_titulo.setGeometry(QtCore.QRect(350, 80, 113, 20))
        self.entrada_titulo.setObjectName("entrada_titulo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.entrada_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_precio.setGeometry(QtCore.QRect(350, 120, 113, 20))
        self.entrada_precio.setObjectName("entrada_precio")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 160, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.entrada_tema = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_tema.setGeometry(QtCore.QRect(350, 160, 113, 20))
        self.entrada_tema.setObjectName("entrada_tema")
        self.boton_registrar_revista = QtWidgets.QPushButton(self.centralwidget)
        self.boton_registrar_revista.setGeometry(QtCore.QRect(290, 530, 171, 41))
        self.boton_registrar_revista.setObjectName("boton_registrar_revista")
        self.checkbox_digital = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_digital.setGeometry(QtCore.QRect(350, 200, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkbox_digital.setFont(font)
        self.checkbox_digital.setObjectName("checkbox_digital")
        self.combo_frecuencia = QtWidgets.QComboBox(self.centralwidget)
        self.combo_frecuencia.setGeometry(QtCore.QRect(350, 240, 111, 22))
        self.combo_frecuencia.setObjectName("combo_frecuencia")
        self.combo_frecuencia.addItem("")
        self.combo_frecuencia.addItem("")
        self.combo_frecuencia.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 240, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(300, 280, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.radio_basico = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_basico.setGeometry(QtCore.QRect(350, 280, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radio_basico.setFont(font)
        self.radio_basico.setChecked(True)
        self.radio_basico.setObjectName("radio_basico")
        self.radio_accesorio = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_accesorio.setGeometry(QtCore.QRect(350, 310, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radio_accesorio.setFont(font)
        self.radio_accesorio.setObjectName("radio_accesorio")
        self.radio_promocional = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_promocional.setGeometry(QtCore.QRect(350, 350, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radio_promocional.setFont(font)
        self.radio_promocional.setObjectName("radio_promocional")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 400, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.boton_seleccionar_imagen = QtWidgets.QPushButton(self.centralwidget)
        self.boton_seleccionar_imagen.setGeometry(QtCore.QRect(340, 400, 161, 31))
        self.boton_seleccionar_imagen.setObjectName("boton_seleccionar_imagen")
        self.label_imagen = QtWidgets.QLabel(self.centralwidget)
        self.label_imagen.setGeometry(QtCore.QRect(540, 410, 201, 121))
        self.label_imagen.setText("")
        self.label_imagen.setObjectName("label_imagen")
        self.label_error_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_error_titulo.setGeometry(QtCore.QRect(480, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_error_titulo.setFont(font)
        self.label_error_titulo.setObjectName("label_error_titulo")
        self.label_error_precio = QtWidgets.QLabel(self.centralwidget)
        self.label_error_precio.setGeometry(QtCore.QRect(480, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_error_precio.setFont(font)
        self.label_error_precio.setObjectName("label_error_precio")
        self.label_error_tema = QtWidgets.QLabel(self.centralwidget)
        self.label_error_tema.setGeometry(QtCore.QRect(480, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_error_tema.setFont(font)
        self.label_error_tema.setObjectName("label_error_tema")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Introduce los datos de la nueva revista"))
        self.label_2.setText(_translate("MainWindow", "titulo:"))
        self.label_3.setText(_translate("MainWindow", "precio:"))
        self.label_4.setText(_translate("MainWindow", "tema:"))
        self.boton_registrar_revista.setText(_translate("MainWindow", "REGISTRAR REVISTA"))
        self.checkbox_digital.setText(_translate("MainWindow", "digital"))
        self.combo_frecuencia.setItemText(0, _translate("MainWindow", "semanal"))
        self.combo_frecuencia.setItemText(1, _translate("MainWindow", "quincenal"))
        self.combo_frecuencia.setItemText(2, _translate("MainWindow", "mensual"))
        self.label_5.setText(_translate("MainWindow", "frencuencia:"))
        self.label_6.setText(_translate("MainWindow", "tipo:"))
        self.radio_basico.setText(_translate("MainWindow", "basico"))
        self.radio_accesorio.setText(_translate("MainWindow", "incluye accesorio"))
        self.radio_promocional.setText(_translate("MainWindow", "promocional"))
        self.label_7.setText(_translate("MainWindow", "imagen:"))
        self.boton_seleccionar_imagen.setText(_translate("MainWindow", "SELECCIONAR IMAGEN"))
        self.label_error_titulo.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_error_precio.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_error_tema.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

